nlewo/nix2container

default.nix

Right now these scripts depend on `/bin/sh`, which may not exist. `writeShellScriptBin` adds a proper shebang to these scripts.

use writeShellScriptBin and fix typos

---

nix/layers_test.go
nix/tar.go
nix/tar_test.go
nix/utils.go
nix/utils_test.go
tests/default.nix

We actually create all intermediate directories and set their
permissions to 755.
Fixes https://github.com/nlewo/nix2container/issues/12

Explicitly create /nix et /nix/store in the tar archive

---

default.nix

closes: #18
@nlewo this works on multi-user install, not sure if it works the same way on daemon install or if it depends on a special `nix.conf`, though.

imp: add source credentials

---

.github/workflows/golangci-lint.yml
cmd/layers.go
cmd/utils.go
default.nix
nix/image.go
nix/tar_test.go
types/types.go

This is to homogeneise the CLI: almost all others arguments are JSON files.

cmd: provide rewrites via a JSON file instead of CLI args

---

default.nix
examples/default.nix
examples/nix.nix
tests/default.nix

This allows to initialize the Nix database into the image in order to
be able to use Nix from the container.
The behavior is similar to `dockerTools.buildImageWithNixDB`.

Add initializeNixDatabase argument to buildImage

---

README.md
default.nix
examples/bash.nix
examples/nginx.nix
examples/nix.nix
examples/openbar.nix

Since the nix2container beginning, the nix2container contents behavior
differed from the dockerTools.buildImage behavior.
See https://github.com/NixOS/nixpkgs/pull/179801 for details.

Rename contents to copyToRoot

---

cmd/image.go
nix/image.go
types/types.go

Fix #34 
Tested on my Raspberry Pi 4. Result [here](https://github.com/lourkeur/hostapd-mana.docker/pkgs/container/hostapd-mana.docker/39323653?tag=latest-aarch64-linux) Unfortunately, Github does not provide aarch64 runners or allow binfmt so I cannot write tests.

buildImage: detect architecture

---

examples/from-image.nix
examples/perms.nix
flake.nix
nix/tar.go
tests/default.nix

Fixes #45 
I ran the same sample code provided in the issue with this fix applied and got the expected results (no file permissions modified).

fix: evaluates perms regular expression when applying permissions

---

examples/default.nix
examples/ownership.nix
nix/layers.go
nix/tar.go
tests/default.nix
types/types.go

Fixes #44 
This PR adds four new fields: `Uid`, `Gid`, `Uname`, and `Gname`. They allow modifying their respective ownership permissions on paths. The default behavior of keeping non-matched files as "0/0/root/root" is maintained for backward compatibility. The only other change is that specifying `mode` is now optional; this is to allow changing ownership while still keeping the default umask. 
This PR includes the permission fix from #46. Feel free to close that one and merge this if it makes things cleaner.

feat: adds support for overriding path owner

---

default.nix
examples/default.nix
examples/nix-user.nix
tests/default.nix

Fixes #50 
Adds two new arguments to `buildImage` which allow controlling ownership of `/nix`. By default, the ownership stays with root if the arguments are not specified. 
The only other change this introduces is moving the `customizationLayer` to the end of the layer list instead of the beginning. This ensures that ownership of `/nix/store` remains with the desired user. As far as I know, this shouldn't be a breaking change. All tests are passing.

feat: allows controlling ownership of /nix

---

default.nix
tests/default.nix

The `0700` permissions are too restrictive and prevent other users from executing stuff in the store.

fix: fix wrong permissions when initializing nix database

---

default.nix
flake.nix
nix/graph.go
nix/tar_test.go
nix/utils.go

This build flag allows to publish an image on a case insensitive FS. Otherwise, hash can differs as detailled in
https://github.com/nlewo/nix2container/issues/37
Fixes !37
@nktpro it would be nice if you could test if it fix your issue?
I still need to ensure it's a good idea to always patch the `nix2container` binary and Skopeo on Darwin... TBH, i'm a bit confused with multiarch containers which are built and pushed on different architectures :upside_down_face:

Add the build flag useNixCaseHack

---

nix/image.go
nix/image_test.go

The current behavior is to leave the ImageV1 `rootfs.type` empty. This leads to some error with external tools like Singularity which fail to run the image.
Setting the Rootfs type in the image metadata to "layers" is mandatory according to the documentation:
https://github.com/opencontainers/image-spec/blob/main/config.md?plain=1#L210-L218

Inject missing rootfs type "layers" in container metadata

---

nix/graph.go

.Size() is otherwise not a reliable indicator of identical contents, see https://pkg.go.dev/io/fs#FileInfo.
In particular, without this duplicate directories cause failures on btrfs/zfs.

addFileToGraph: Only do Size() comparisons on duplicate regular files.

---

README.md
cmd/image.go
default.nix
examples/alpine-manifest.json
examples/default.nix
examples/from-image-manifest.nix
examples/get-manifest.nix
flake.nix
nix/image.go
tests/default.nix

Basic implementation of what I proposed in #76. ~~I've only tried Docker.io images, so I don't know if there's any implication for OCI-first registries like Quay.io, but if there is, I'd expect that's something to tackle in a follow-on regardless.~~ Nevermind, I've now pulled OCI images from Harbor with this, and it seems to work great.
This is mergeable as it is, but a few potential areas for discussion:
- I wasn't sure about whether to consume the skopeo default `inspect` JSON vs the `--raw` one. The default is nice because it actually includes the image path in it, meaning that that doesn't have to be specified again for the nix function call, but I settled on the raw one as it seems like the Go code was already set up to parse that, and it's also more terse.
- There's some confusion …

Pull image layers from a supplied manifest.

---

default.nix

`closureGraph` is extended with an ignore argument which will filter out the config file when needed.
The resulting graph is both passed to nix2container-bin and makeNixDatabase -- ensuring that both contain the same paths.
The `--ignore` flag of the nix2container-bin is not used anymore.
https://github.com/nlewo/nix2container/issues/94

Fixes #94: do not include config file in nix database.

---

default.nix

Mentioned in https://github.com/nlewo/nix2container/pull/77#issuecomment-1579042791; not really essential but might be a nice improvement.
Main thing to watch for is that now `jq` is required for all the little scripts, but it is just a few hundred kb, so I don't think this is a major cost.

Add writeSkopeoApplication helper.

---

default.nix

default.nix: fix evaluation on macos

---

default.nix
flake.lock

Fixes  #131
flake.lock change is required to use `excludeShellChecks` attribute

fix: multiple shell args

---

nix/image_test.go
nix/layers_test.go
nix/tar.go
nix/tar_test.go

I investigated why my nginx worked fine on my host nixos but not in the container. I found that nginx is patched to better handle files inside the nix store, but one of the condition is that mtime should be 1. I checked /nix/store on my system and yes all files have mtime 1, then I checked /nix/store files inside the container and mtime is 0
https://github.com/NixOS/nixpkgs/blob/194846768975b7ad2c4988bdb82572c00222c0d7/pkgs/servers/http/nginx/nix-etag-1.15.4.patch#L43
After changing modification time from 0 to 1 in the nix2container that patch started to work as expected

Change modification time to be consistent with nix store

---

cmd/image.go
default.nix
examples/created.nix
examples/default.nix
nix/image.go
tests/default.nix
types/types.go

Implements #89.
Like `nixpkgs.dockerTools.buildImage`, let `nix2container.buildImage` take an optional `created` argument that will be set on the resulting image. For backwards compatibility, it defaults to `"0001-01-01T00:00:00Z"`.
I did not implement support for passing `"now"`, as I don't need it.
(cherry picked from commit ffafa5df41829395609c51b25853fd7bdf154e5e)

Allow setting the Created timestamp

---

default.nix

It looks like GitHub changed the way their are generating patches. Here are differences:
diff c2254c998433cf02af60bf0292042bd80b96a77e.patch /nix/store/xk6z74qc073dvs1ngvk58qqby73q6yx9-c2254c998433cf02af60bf0292042bd80b96a77e.patch
18c18
< index 0000000000..46e737dc78
---
> index 000000000..46e737dc7
229c229
< index 0bae8b2599..34cf925c29 100644
---
> index 0bae8b259..34cf925c2 100644

Update the Skopeo patch hash

---

default.nix

The hash of the patch changed again. I saw #151 but I got a different hash value. After reading through https://github.com/NixOS/nixpkgs/issues/257446 I've found a proposal that seems to be stable enough to try.

fix: stable patch fetch

---

README.md
cmd/layers.go
cmd/utils.go
default.nix
examples/default.nix
examples/metadata.nix
nix/image.go
nix/image_test.go
nix/layers.go
nix/layers_test.go
tests/default.nix
types/types.go

This adds an optional `metadata` argument to `buildLayer` which allows the corresponding information strings to be set in the image history.

Allow layer author, comment, and created-by metadata to be set

---

flake.lock
flake.nix

Manually handling `system` is similar to using `flake-utils`. So it's nice to have fewer inputs.
Moved `defaultPackage` to `packages.default` since the former is deprecated.

Remove flake-utils

---

default.nix

Use `runCommandLocal` instead of `runCommand`, this should enforce that these json files containing filesystem hashes are generated on the host machine after the inputs are available.

Ensure layers.json and image-*.json are built locally and not cached
